language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: XtJ2HhZqj55GThaKTUEtypjyhrzIva5yCyx8dKNduFbbtBuHqQjNlEQTN2JPfVY+b7gfluUoplJvwiBYEo9j8DOMccml9PzPnVpLqUiL4R8nn7LkxF4jXdLRUFzGH5eQh3f21yLGbH3vZU610lb62N+X9YqaiIqlWLNjAFwZw3peCYewYPh7/NHVfruGFkZ2ysw7ITTQdUnNf6+35/02KUU9kuZrioPyxtKuEHj9KEoJpCf9yKdM926LK8SLBUdIfvvp9CPZaJdeaaIOPY9wfhxZb+tM0Q+zteBC8tM0dZSCevIeTtJ75/J4A2fcOyvhFUL0e5hws42G311RcYY+l9Tmd18/JxDLRVtHglT9p9iWenK/49/0W7qDaaKN3CPnhgntoTuqdikyCf+CaRhNRDDxW7GzYaDfXLc85zpFMQtkFakB+AeOj/jQ/Giu3EcA6nPvc7Tp7bzrxMy1nUzNJj+w49J3f9V9JkjpvgnHa0UziKsxocYes5YqHntfDyOX5vrp6oRQTGQmDmshgFFiplNjfrbhYuhsJTbkB2IWTMtoHpwgRXO7R0hFIuC3N1HF3zO2YK4nuK6zuwEG3JcNH5/BJzlbUtwCWws+wWYF2HA7kF78ysc+AyERAYivTsRXkTqd7UtBaFGZ7a21egYbhyN+bd26AWNQws4JhVUrrA4=
  app: deal-hacker
  on:
    repo: RyanOkamuro/deal-hacker
