language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: NtykOjivRYr95AE5LBubRE+l0g8aoZnIzeNydsTRX3laT01N52jfZtPb7YW063UvwCYTSe3yOyfAPikG/muN2X0nuYvpOa/7CU/yqn5+/OekBuvzcukPBwhlUHPDxtB+clTfiBth3eXa0VofvSe/HFmo5yOy+QJEn+gUFSAXmCGSQjN9o7LPDB4tVtgPTLeeA+Rt5JzBRQ5nXR0bJ1zrECss8970Os7b4AZJ1lRStNSSiNBzAKZr4ognxokT+lbYjw/Pbb8tLKMhgSjuF0r5U5NVPtevGiK8/1+gFqP74WnqtKu/w767smzLP4m9DG6ThOcH0pr/C0ABSdBB8BWVXSkkCwUv8vCEJ7BGdhatPkoPsbtQi1mneI+lN1LAz/QA6b0SeqXYxPiN6SLJ7ALJQ9fiVLsVCfuL1QoxrCbekCH6SAQoVZ/38pTcfAPkOqgGxWVY0AdMnIRZHY/PUQ8IZRI9Q6xs22fjdQnwljNvf0aEPinM3JVqdkO9j/Fk7nreqphS23V9+DTYbR1Tn0jzhXKZgn6mZvM8BBh01LRTkODURpkxci5qdHl7hVOHfpGIe0yEpnrvstg4sQ/SM4ljYJfdSoxidsqSQVIL+3uB/nCnrhYmN5mDlQciU1fA4HQR4FSuap/7frGjbuHxi31SKrtpDwN0cjo+8UEvudCV3ys=
  app: deal-hacker
  on:
    repo: RyanOkamuro/deal-hacker
