language: node_js
node_js: node
cache:
  directories:
  - node_modules
script:
- npm test
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 7I+zolk46eX0ajPMnoeBuz/1lHYNUlBI6yBWybwuYnMFX/vJNKEs6AR6DW0aDn+WeEfAygN6GOmspVIms3l+TdE/4lWCltvq7IbKEHzvvvDSBdyLIPWwzugCGbWaEqf7oOGlr6fdnIFZx5r1oGGUfkXkGkggx93RDo4bgkCBmSQaYbX0Bm89R1yadAJ1q7HomO9RdUeIw/K3dN10zGEFvTrR/OyIoEszLbnwk4FRDakn5pAmrZAzhHcPoHg3btVilAh+l67SreFbmthI4N0FyW3OG5Zf12Z2PsLmswzVNp9XyFzar2wW0qR1V1ZewcB0AG0oxgajhjkHonno+xDgDgbN5LnBAG90B60rEwN1ntZoPnR2hyZnZF1HWq79tSC6JBlvSWUJBa97G8EneYr0v0eQucxjKXtGEPGj07utgoXCJVZeo43KIfdW+Df1fiKX78V8qnKQ4rgtnBp+9ND33AJU0ZUh8wlPMApPNg7KLaUitTHEmuwrv9MHyvKgJE+fSE8hRd0cH5ZOp0+PEctWbnHawOyLZX9IXgOZG1+YIsiAwV+M0rNUzxgqXtLWn/R9VvAWdElwV60TXdmzjzz5btVKR0LkMt0fhbRXHNnZR/k2nE/Qp7nXmDcP7WqJ4v7oSsRvn8XE4nuVey2/QhILbDZOLiscPMDn7x0RgbmHjt0=
  app: deal-hacker
  on:
    repo: RyanOkamuro/deal-hacker
