language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 4Qi2nCvaC/MQ13mxzGvFDF6daxTwx10a6LwWANJSbCRIWxsI3We7a3Mqvk4ItX65qaBWhWaVLPaKqxP6Bm7YMbidlcsQwR52Le8SloOrgKx6IRvQKdYC0uLwqWUAa9M7VRCRaFSztDHV+ep6hJ0rVJkowdcqmhhkx71izxQLcL5eevZ9WkZx++v3/XfpoV29gzpBdSg/xc9AC5bhGGGiZB157NNunZ9/MubhkIFiEmQaUh1XchKEpeN7Y3s2viRdNylzIJ52l4PuswLipvZPzZpOz69RNZesLsZtXNRHrFS85wTqNwVuk7d7PU42ePJ4GBt7QitPKGzPyM5WA5LwR0T04Ug4nsxZeNPSjFlCuwekQvjZVTSjMJF9cA/Fral/xHeYQInm7aUr5Ieaeh24jV3PRVBcD5X/VoPJWHFOAQGqy172amLpuJWN0Dlew+0pa/LA9wCpkIMM/LxQ2jGBFZLTUeY0XBLyi1Uzx6nsa81V1uo0z5L7tNNTjMZEdeWIvqIJo6g7zJygvP+nOUH0tU2DIK4BhRu5s4i7KOBs6LNIkicUL1H4jOs4Wv5N+nl8xC7X4YK+V/iLLnCtiF0byZfUskKZOYZqKwr0Ep+ka0QXnT3kRGBQ6/RGBwHUcFxk/3L/E3gODnPw6QEsbK4fo9AGhK++FqHTeFzOaRFuANM=
  app: deal-hacker
  on:
    repo: RyanOkamuro/deal-hacker
