language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: SxooIhojZCcvPyBC9QmBquHH/PkBO9CISPhXmFnBnMf5uAEDBzqGkKesMj0H7/QxwEJPVsEolVSikAalYFcL0uz6v4n+tdzBbgl6Co+cJREcnt+zrsAkEkNdZpj26LIkptwvp3CZ0Q/387In0WZVlHjzsAR16xSCxzIKpvV8oMBDWe2dgRb4fdb1b2luLbx5SD+zp6wzhbniFvNaBtbyL8CBBdx+nbfq1gSQ5GgsukRGwq7yCoNUMcoNgxusqTn+gK3WtfAwbmFjeQAQ+2oegDdDjJErOsbGMu3KZ1+6aZIipPiZUl64eRUi7NSiXIHU/Ue3Ez01SqSiQ3OlbL70jD6GskFS9fDj+pgnWxwmvUCnFSm+DJViIOt4NvyugSxdB2Eks+orXsuj8qFnXWr8iw9T1IcEN5QL+XxpgV8jCIOHV9ObCK7+Lnn8I39UFip/C1/Wk1uQHPAKC0BijCPbDMKvMrDRmZ8G8ZhWqrHh4HmDbIr8Dsr4QW/zIhOFJVHt0VasT1p5CQB1aZpFDFzH3xl5q4QYxIdmhj7DBh2EijK3/OlM1wE7a3oZuDwCAOA1gBJsIMER4+/r08r+eQIDAv1k4QvO3Ryg7Coc5LKRjdkkz/MUqV62MHMgON00oxaVxmsePdBkrG66YPgjsMdccaNFgf31pmB76DATApq96VM=
  app: deal-hacker
  on:
    repo: RyanOkamuro/deal-hacker
